name: aqarat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  ionicons: ^0.2.2
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  carousel_slider: ^4.2.1
  firebase_auth: ^4.6.2
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^5.0.11
  google_nav_bar: ^5.0.6
  google_maps_flutter: ^2.3.0
  flutter_localization: ^0.1.12
  intl: ^0.17.0
  shared_preferences: ^2.1.2
  lottie: ^2.3.2
  flare_splash_screen: ^4.0.0
  flutter_inappwebview: ^5.7.2+3

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
